<?php

namespace Visions\VisionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisionRepository extends EntityRepository
{
}
