<?php

namespace Libetto\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterestInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestInRepository extends EntityRepository
{
}
