<?php

namespace Libetto\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterestInMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestInMapRepository extends EntityRepository
{
}
