#visions_redmine:
#    resource: "@VisionsRedmineBundle/Controller/"
#    type:     annotation
#    prefix:   /

api:
    resource: "@VisionsAPIBundle/Resources/config/routing.yml"
    prefix: /api     
    type: rest
    
visions_api_redmine:
    resource: "@VisionsAPIRedmineBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /api  

_welcome:
    pattern:   /
    defaults:  { _controller: VisionsDashboardBundle:Default:index }

visions_dashboard:
    resource: "@VisionsDashboardBundle/Controller/"
    type:     annotation
    prefix:   /


visions_user:
    resource: "@VisionsUserBundle/Controller/"
    type:     annotation
    prefix:   /login



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /profile

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


visions_content:
    resource: "@VisionsContentBundle/Controller/"
    type:     annotation
    prefix:   /

visions_core:
    resource: "@VisionsCoreBundle/Controller/"
    type:     annotation
    prefix:   /

visions_doc:
    resource: "@VisionsDocBundle/Controller/"
    type:     annotation
    prefix:   /doc

visions_vision:
    resource: "@VisionsVisionBundle/Controller/"
    type:     annotation
    prefix:   /vision

#Visions_user:
#    resource: "@VisionsUserBundle/Controller/"
#    type:     annotation
#    prefix:   /