libetto_user:
    resource: "@LibettoUserBundle/Controller/"
    type:     annotation
    prefix:   /

#m_user:
#    resource: "@MUserBundle/Controller/"
#    type:     annotation
#    prefix:   /m
#
#m_company:
#    resource: "@MCompanyBundle/Controller/"
#    type:     annotation
#    prefix:   /m
#
#m_customer:
#    resource: "@MCustomerBundle/Controller/"
#    type:     annotation
#    prefix:   /m
#
#m_product:
#    resource: "@MProductBundle/Controller/"
#    type:     annotation
#    prefix:   /m

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile