security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                always_use_default_target_path: true
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login 
                check_path: fos_user_security_check
                default_target_path: /
            logout:
                path: fos_user_security_logout
                target: /
                invalidate_session: false
            anonymous:    true
 
    access_control:
      - { path: ^/profile/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/contact/, roles: ROLE_USER }
      - { path: ^/customer/, roles: ROLE_USER }
      - { path: ^/item/, roles: ROLE_USER }
      - { path: ^/maintenance/, roles: ROLE_ADMIN }
      - { path: ^/supplier/, roles: ROLE_USER }
      - { path: ^/user/, roles: ROLE_USER }
       # - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/admin/, role: ROLE_ADMIN }
       # - { path: ^/customer/$, role: ROLE_USER }
       # - { path: ^/user/$, role: ROLE_USER }
       # - { path: ^/supplier/$, role: ROLE_USER }
       # - { path: ^/maintenace/$, role: ROLE_USER }
       # - { path: ^/dashboard/$, role: ROLE_USER }
        