maintenance_homepage:
    pattern:  /
    defaults: { _controller: LibettoMaintenanceBundle:Default:index }

master_list:
    pattern: /master/list
    defaults: { _controller: LibettoMaintenanceBundle:Master:list }

master_edit:
    pattern: /master/edit/{cId}
    defaults: { _controller: LibettoMaintenanceBundle:Master:edit,cId:null }

master_delete:
    pattern: /master/delete/{cId}
    defaults: { _controller: LibettoMaintenanceBundle:Master:delete }

master_import:
    pattern: /master/import
    defaults: { _controller: LibettoMaintenanceBundle:Master:import }

master_refresh:
    pattern: /master/refresh
    defaults: { _controller: LibettoMaintenanceBundle:Master:refresh }

testpage_ajax:
    pattern: /test
    defaults: { _controller: LibettoMaintenanceBundle:JQUITest:test }

load_ajax:
    pattern: /loadAjax
    defaults: { _controller: LibettoMaintenanceBundle:JQUITest:loadAjaxTable }

load_ajax_mastertable:
    pattern: /loadAjaxMaster
    defaults: { _controller: LibettoMaintenanceBundle:JQUITest:loadAjaxMaster }
