<?php

namespace Libetto\MaintenanceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributesRepository extends EntityRepository
{
}
