<?php

namespace Libetto\MaintenanceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterRepository extends EntityRepository
{
    
    public function getRowsSortetdByTabelnameAndSortindex(){
        
        $query = $this->createQueryBuilder('m')
                ->orderBy('m.tablename', 'ASC')
                ->orderBy('m.orderid', 'ASC')
                ->getQuery();
        
       return count($query->getResult());
        
    }
}
