#parameters:
#    libettosecuritycontext.class: Visions\CoreBundle\Entity\BaseTable

#services:
#    libettosecuritycontext:
#        class:        "%libettosecuritycontext.class%"
#        arguments:    ["@service_container"]
        