api_customers:
    type:     rest
    prefix:   /
    resource: Libetto\APIBundle\Controller\CustomersController   
    
api_users:
    type:     rest
    prefix:   /    
    resource: Libetto\APIBundle\Controller\UsersController   
    
api_products:
    type:     rest
    prefix:   /
    resource: Libetto\APIBundle\Controller\ProductsController      