<?php

namespace Libetto\ItemBundle\Entity;

use Libetto\CoreBundle\Entity\BaseTableRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends BaseTableRepository {
    
}