parameters:
#    libetto_core.example.class: Libetto\CoreBundle\Example

services:
#    libetto_core.example:
#        class: %libetto_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
