api_users:
    type:     rest
    prefix:   /redmine    
    resource: Visions\APIBundle\Controller\UsersController   

api_redmine_projects:
    type:     rest
    prefix:   /redmine    
    resource: Visions\APIBundle\Controller\RedmineProjectsController 